### ISSUE TITLE
TLS Connector Builder

### ISSUE THREAD

**Issue by yoshuawuyts** [dbcfd/tls-async#2]
## Description
Building a TLS Connector in the current setup requires some effort. Looking at [an example](https://github.com/dbcfd/tls-async/blob/master/examples/download-rust-lang.rs):

```rust
let cx = TlsConnector::builder().build().expect("Could not build");
let cx = tls_async::TlsConnector::from(cx);
```

There are two separate structs named `TlsConnector`. It'd be nice if tls-async had a single builder for this:

```rust
let cx = tls_async::TlsConnector::builder().build()?;
```

## Possible Implementation
This probably requires moving `TlsConnector` to its own file, creating a `TlsConnectorBuilder` struct and wrapping the native-tls struct to shadow its methods.

---

I hope this makes sense. I was reading the example and got a little confused. I'd be happy to help with the implementation of this if you think it's a good idea :sparkles:

**Comment by dbcfd** [comment]
The docs (and the example) were forked from tokio-tls, and could definitely use work. The re-export you mention in #1 might help improve this workflow, especially when combined with improved documentation.

I'm inclined to try that before shadowing the native-tls struct.

**Comment by dbcfd** [comment]
@yoshuawuyts Shadowing of native-tls appears in https://github.com/dbcfd/tls-async/pull/4
